# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: npbuf/type/ndarray.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from npbuf.type import dtype_pb2 as npbuf_dot_type_dot_dtype__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='npbuf/type/ndarray.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18npbuf/type/ndarray.proto\x1a\x16npbuf/type/dtype.proto\"P\n\x07ndarray\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\x15\n\x05\x64type\x18\x65 \x01(\x0b\x32\x06.dtype\x12\r\n\x04\x64\x61ta\x18\xc9\x01 \x01(\x0c\x12\x10\n\x07strides\x18\xad\x02 \x03(\x03\x62\x06proto3')
  ,
  dependencies=[npbuf_dot_type_dot_dtype__pb2.DESCRIPTOR,])




_NDARRAY = _descriptor.Descriptor(
  name='ndarray',
  full_name='ndarray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='ndarray.shape', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='ndarray.dtype', index=1,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ndarray.data', index=2,
      number=201, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strides', full_name='ndarray.strides', index=3,
      number=301, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=132,
)

_NDARRAY.fields_by_name['dtype'].message_type = npbuf_dot_type_dot_dtype__pb2._DTYPE
DESCRIPTOR.message_types_by_name['ndarray'] = _NDARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ndarray = _reflection.GeneratedProtocolMessageType('ndarray', (_message.Message,), dict(
  DESCRIPTOR = _NDARRAY,
  __module__ = 'npbuf.type.ndarray_pb2'
  # @@protoc_insertion_point(class_scope:ndarray)
  ))
_sym_db.RegisterMessage(ndarray)


# @@protoc_insertion_point(module_scope)
